language: java
env:
  - TESTFOLDER=chronos-web
  - TESTFOLDER=chronos-agent
script: "mvn clean test -pl $TESTFOLDER"
after_success:
  - mvn clean cobertura:cobertura coveralls:report -DignoreTrivial=true
